import '../mocks/child_process';
import '../mocks/colors';
import '../mocks/es';
import '../mocks/express';
import '../mocks/fs';
import '../mocks/http-proxy';
import '../mocks/net';
import '../mocks/os';
import '../mocks/ws';
